path: '/content/gdrive/My Drive/ComputerVisionEngineer/ObjectDetectionYolov8GoogleColab/data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

names:
  0: Ambulance
  1: Bus
  2: Car
  3: Motorcycle
  4: Truck

